config/routes.rb
Rails.application.routes.draw do

  resources :users

  root to: "home#index"
  get '/settings', to: 'settings#index'
  get '/friends', to: 'friends#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create'

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :schedule
  has_one :user, through => :schedule
  belongs_to_many :circles
end

app/models/circle.rb
class Circle < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :blocks
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  has_many :blocks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email

  attr_accessible :name, :email, :password, :password_confirmation
  has_many :schedules
  has_many :circles
  has_many :blocks, :through => :schedules
  has_many :users, :through => :circles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to login_url, alert: "Not authoriezd" if current_user.nil?
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_email(params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to "", notice: "logged in"
        else
            flash.now.alert = "Email or password is invalid"
            redirect_to "/login"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to "", notice: "Logged out!"
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        # render text: params[:user].inspect
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user, notice: "Thank you for signing up!"
        else
            redirect_to ""
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        redirect_to ""
    end

    def show
        @user = User.find(params[:id])
    end


    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/index.html.erb
<h2>Friends</h2>

<%= link_to "home", controller: "home" %>

app/views/home/index.html.erb
<h1>Home</h1>
<h2>Welcome, <%= session[:user_id] %> </h2>

  <% @users.each do |u| %>
    <tr>
      <td><hr>email: <%= u.email %></td><br/>
      <td>name: <%= u.name %></td><br/>
      <td>pass: (hidden or bugged? who knows)<%= u.password %></td><br/>
      <td><%= link_to 'Destroy', user_path(u), method: :delete %><hr></td>
      <br/>
    </tr>
  <% end %>


<%= link_to "settings", "settings" %>
<%= link_to "friends", "friends" %>
<%= link_to "login", "login" %>
<%= link_to "logout", "logout" %>
<%= link_to "register", "signup" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/settings/index.html.erb
<h2>Settings</h2>

<h3>Blocked List:</h3>



<%= link_to "home", controller: "home" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :user, url: users_path do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<hr>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Home', root_path %>